apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-application
  labels:
    app: nodejs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: public.ecr.aws/i8f6z8g5/akshaya/backend:latest
          ports:
            - containerPort: 3500
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: MONGO_PASSWORD
            - name: MONGO_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGODB_URL
