apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
    - name: mongodb-service
      protocol: TCP
      port: 27017
      targetPort: 27017
